readme = open('/root/chaintail/README.md', 'w')

lines = [
"# ChainTrail\n",
"\n",
"> Open Source Bitcoin AML Forensics and Transaction Trail Tracker\n",
"\n",
"[

![License: MIT](https://img.shields.io/badge/License-MIT-blue.svg)

](LICENSE)\n",
"[

![Node.js](https://img.shields.io/badge/Node.js-22-green.svg)

](https://nodejs.org)\n",
"[

![TypeScript](https://img.shields.io/badge/TypeScript-5.3-blue.svg)

](https://typescriptlang.org)\n",
"[

![PostgreSQL](https://img.shields.io/badge/PostgreSQL-17-336791.svg)

](https://postgresql.org)\n",
"\n",
"ChainTrail is a real-time Bitcoin transaction monitoring and AML forensics platform.\n",
"\n",
"---\n",
"\n",
"## Architecture\n",
"\n",
"```mermaid\n",
"flowchart TD\n",
'    A["Bitcoin Network"] -->|"WebSocket"| B["mempool-watcher"]\n',
'    B --> C[("PostgreSQL")]\n',
'    B --> D[("Redis")]\n',
'    C --> E["graph-tracer"]\n',
'    C --> F["clustering"]\n',
'    C --> G["threat-feeds"]\n',
'    E --> H["REST API :3001"]\n',
'    F --> H\n',
'    G --> H\n',
'    H --> I["Dashboard :3000"]\n',
'    G -->|"alerts"| J["Telegram / Discord"]\n',
"```\n",
"\n",
"---\n",
"\n",
"## Graph Tracer Flow\n",
"\n",
"```mermaid\n",
"flowchart TD\n",
'    A["Target Address"] --> B["Fetch transactions"]\n',
'    B --> C["Save to PostgreSQL"]\n',
'    C --> D["Run recursive CTE"]\n',
'    D --> E["Hop 1 - direct senders"]\n',
'    E --> F["Hop 2 - senders of senders"]\n',
'    F --> G["Hop N - up to max hops"]\n',
'    G --> H["Check against threat intel"]\n',
'    H --> I{"Match found?"}\n',
'    I -->|"Yes"| J["Flag and raise risk score"]\n',
'    I -->|"No"| K["Mark clean"]\n',
'    J --> L["Return result with risk 0-100"]\n',
'    K --> L\n',
"```\n",
"\n",
"---\n",
"\n",
"## Risk Scoring\n",
"\n",
"```mermaid\n",
"flowchart LR\n",
'    A["Address"] --> B{"In threat intel?"}\n',
'    B -->|"Yes"| C["Score from category"]\n',
'    B -->|"No"| D{"Near flagged address?"}\n',
'    C --> H["Final score 0-100"]\n',
'    D -->|"Yes"| F["Score decays per hop"]\n',
'    D -->|"No"| G["Score zero"]\n',
'    F --> H\n',
'    G --> H\n',
'    H --> I{"Level"}\n',
'    I -->|"80+"| J["CRITICAL"]\n',
'    I -->|"60-79"| K["HIGH"]\n',
'    I -->|"30-59"| L["MEDIUM"]\n',
'    I -->|"0-29"| M["LOW"]\n',
"```\n",
"\n",
"---\n",
"\n",
"## Database Schema\n",
"\n",
"```mermaid\n",
"erDiagram\n",
"    transactions {\n",
"        uuid id PK\n",
"        text txid\n",
"        int block_height\n",
"        bigint fee\n",
"        boolean is_confirmed\n",
"    }\n",
"    tx_inputs {\n",
"        uuid id PK\n",
"        text txid FK\n",
"        text from_address\n",
"        bigint value_satoshi\n",
"    }\n",
"    tx_outputs {\n",
"        uuid id PK\n",
"        text txid FK\n",
"        text to_address\n",
"        bigint value_satoshi\n",
"    }\n",
"    addresses {\n",
"        uuid id PK\n",
"        text address\n",
"        uuid cluster_id FK\n",
"        int risk_score\n",
"    }\n",
"    clusters {\n",
"        uuid id PK\n",
"        text label\n",
"        text risk_level\n",
"    }\n",
"    threat_intel {\n",
"        uuid id PK\n",
"        text address\n",
"        text label\n",
"        text category\n",
"        int confidence\n",
"    }\n",
"    alerts {\n",
"        uuid id PK\n",
"        text address\n",
"        text txid\n",
"        text severity\n",
"    }\n",
'    transactions ||--o{ tx_inputs : "has"\n',
'    transactions ||--o{ tx_outputs : "has"\n',
'    clusters ||--o{ addresses : "groups"\n',
"```\n",
"\n",
"---\n",
"\n",
"## Features\n",
"\n",
"| Feature | Description |\n",
"|---------|-------------|\n",
"| Live Mempool Stream | WebSocket to mempool.space - every Bitcoin tx pushed instantly |\n",
"| Graph Tracer | Trace fund flows N hops deep using PostgreSQL recursive CTEs |\n",
"| Address Clustering | Group related addresses using Union-Find heuristic |\n",
"| Risk Scoring | Score addresses 0 to 100 based on proximity to bad actors |\n",
"| Threat Intel | 1258+ known bad actors including WannaCry and Lazarus Group |\n",
"| Webhook Alerts | Telegram and Discord alerts when watched addresses hit mempool |\n",
"| Mobile Dashboard | Responsive Next.js UI works on Android |\n",
"| REST API | 14 endpoints for programmatic access |\n",
"\n",
"---\n",
"\n",
"## Project Structure\n",
"\n",
"```\n",
"chaintail/\n",
"├── packages/\n",
"│   ├── node-connector      Bitcoin RPC and Blockstream API\n",
"│   ├── mempool-watcher     Live WebSocket stream\n",
"│   ├── graph-tracer        Recursive graph traversal\n",
"│   ├── clustering          Union-Find clustering engine\n",
"│   ├── threat-feeds        Threat intel and webhooks\n",
"│   ├── api                 Express REST API\n",
"│   ├── shared              Types and DB schema\n",
"│   └── dashboard           Next.js UI\n",
"└── package.json\n",
"```\n",
"\n",
"---\n",
"\n",
"## Quick Start\n",
"\n",
"Prerequisites: Node.js 18+, PostgreSQL 14+, Redis 6+\n",
"\n",
"```bash\n",
"git clone https://github.com/rajeshselvam02/chaintail.git\n",
"cd chaintail\n",
"npm install --legacy-peer-deps\n",
"cp .env.example .env\n",
"```\n",
"\n",
"```bash\n",
"psql -U postgres -c \"CREATE USER chaintail WITH PASSWORD 'chaintail';\"\n",
"psql -U postgres -c \"CREATE DATABASE chaintail OWNER chaintail;\"\n",
"npm run migrate\n",
"cd packages/threat-feeds && npm run sync\n",
"```\n",
"\n",
"```bash\n",
"cd packages/api && npm run dev\n",
"cd packages/mempool-watcher && npm run dev\n",
"cd packages/dashboard && npm run dev\n",
"```\n",
"\n",
"Open http://localhost:3000\n",
"\n",
"---\n",
"\n",
"## API Reference\n",
"\n",
"Base URL: `http://localhost:3001`\n",
"\n",
"| Method | Endpoint | Description |\n",
"|--------|----------|-------------|\n",
"| GET | /api/health | Health check |\n",
"| GET | /api/address/:address | Address info and risk score |\n",
"| GET | /api/trace/:address?hops=3 | Trace fund flow |\n",
"| POST | /api/trace | Trace with options |\n",
"| GET | /api/cluster/:address | Get address cluster |\n",
"| POST | /api/cluster/run | Run clustering |\n",
"| GET | /api/alerts | List alerts |\n",
"| GET | /api/mempool/stats | Mempool statistics |\n",
"| GET | /api/mempool/recent | Recent transactions |\n",
"| GET | /api/threat-intel | List threat intel |\n",
"| POST | /api/threat-intel | Add threat intel |\n",
"| GET | /api/webhooks/watched | Watched addresses |\n",
"| POST | /api/webhooks/watched | Watch an address |\n",
"\n",
"---\n",
"\n",
"## Threat Intelligence\n",
"\n",
"| Source | Category | Count |\n",
"|--------|----------|-------|\n",
"| WannaCry ransomware | Ransomware | 3 |\n",
"| Lazarus Group | Sanctioned | 1 |\n",
"| Silk Road | Darknet | 1 |\n",
"| BitcoinFog and Helix | Mixer | 2 |\n",
"| CryptoScamDB | Scam | 1163 |\n",
"| Public mixer lists | Mixer | 85 |\n",
"| **Total** | | **1258+** |\n",
"\n",
"---\n",
"\n",
"## Android Support\n",
"\n",
"```bash\n",
"pkg install proot-distro\n",
"proot-distro install ubuntu\n",
"proot-distro login ubuntu\n",
"apt install nodejs postgresql redis-server git -y\n",
"```\n",
"\n",
"Then follow the standard installation steps above.\n",
"\n",
"---\n",
"\n",
"## Roadmap\n",
"\n",
"- [x] Live WebSocket mempool stream\n",
"- [x] N-hop recursive graph tracer\n",
"- [x] Address clustering\n",
"- [x] Threat intel sync\n",
"- [x] REST API\n",
"- [x] Mobile dashboard\n",
"- [x] Webhook alerts\n",
"- [ ] D3.js graph visualization\n",
"- [ ] OFAC sanctions auto-sync\n",
"- [ ] Docker compose\n",
"- [ ] Lightning Network support\n",
"- [ ] Ethereum support\n",
"\n",
"---\n",
"\n",
"## License\n",
"\n",
"MIT - Built by [@rajeshselvam02](https://github.com/rajeshselvam02)\n",
]

readme.writelines(lines)
readme.close()
print("README written successfully")
